<?php
       if(isset($_POST['Maggie']))
       {
        x('Maggie');
       }
       if(isset($_POST['Ketchup']))
       {
        x('Ketchup');
       }
       if(isset($_POST['Bourban']))
       {
        x('Bourban');
       }
       if(isset($_POST['Oats']))
       {
        x('Oats');
       }
       if(isset($_POST['Bhujia']))
       {
        x('Bhujia');
       }
       if(isset($_POST['CornFlakes']))
       {
        x('CornFlakes');
       }
       if(isset($_POST['Marie']))
       {
        x('Marie');
       }
       if(isset($_POST['Orie']))
       {
        x('Orie');
       }
       if(isset($_POST['Yippee']))
       {
        x('Yippee');
       }
       if(isset($_POST['Lays']))
       {
        x('Lays');
       }
       if(isset($_POST['Jam']))
       {
        x('Jam');
       }
       if(isset($_POST['Honey']))
       {
        x('Honey');
       }
       if(isset($_POST['Chocos']))
       {
        x('Chocos');
       }
       if(isset($_POST['DarkFantasy']))
       {
        x('DarkFantasy');
       }
       if(isset($_POST['DairyMilk']))
       {
        x('DairyMilk');
       }
       if(isset($_POST['Kurkure']))
       {
        x('Kurkure');
       }
       if(isset($_POST['Pasta']))
       {
        x('Pasta');
       }
       if(isset($_POST['Gems']))
       {
        x('Gems');
       }
       if(isset($_POST['Tomato']))
       {
        x('Tomato');
       }
       if(isset($_POST['Cucumber']))
       {
        x('Cucumber');
       }
       if(isset($_POST['Potato']))
       {
        x('Potato');
       }
       if(isset($_POST['Onion']))
       {
        x('Onion');
       }
       if(isset($_POST['Peas']))
       {
        x('Peas');
       }
       if(isset($_POST['Carrot']))
       {
        x('Carrot');
       }
       if(isset($_POST['LadiesFinger']))
       {
        x('LadiesFinger');
       }
       if(isset($_POST['BottleGuard']))
       {
        x('BottleGuard');
       }
       if(isset($_POST['Chilli']))
       {
        x('Chilli');
       }
       if(isset($_POST['BeetRoot']))
       {
        x('BeetRoot');
       }
       if(isset($_POST['Brinjal']))
       {
        x('Brinjal');
       }
       if(isset($_POST['Ginger']))
       {
        x('Ginger');
       }
       if(isset($_POST['Spinach']))
       {
        x('Spinach');
       }
       if(isset($_POST['CauliFlower']))
       {
        x('CauliFlower');
       }
       if(isset($_POST['Capsicum']))
       {
        x('Capsicum');
       }
       if(isset($_POST['MushRoom']))
       {
        x('MushRoom');
       }
       if(isset($_POST['Cabbage']))
       {
        x('Cabbage');
       }
       if(isset($_POST['DrumStick']))
       {
        x('DrumStick');
       }
       if(isset($_POST['Toothpaste']))
       {
        x('Toothpaste');
       }
       if(isset($_POST['DettolLiquid']))
       {
        x('DettolLiquid');
       }
       if(isset($_POST['Soap']))
       {
        x('Soap');
       }
       if(isset($_POST['Facewash']))
       {
        x('Facewash');
       }
       if(isset($_POST['HFacewash']))
       {
        x('HFacewash');
       }
       if(isset($_POST['Handwash']))
       {
        x('Handwash');
       }
       if(isset($_POST['Shampoo']))
       {
        x('Shampoo');
       }
       if(isset($_POST['CoconutOil']))
       {
        x('CoconutOil');
       }
       if(isset($_POST['Engage']))
       {
        x('Engage');
       }
       if(isset($_POST['Perfume']))
       {
        x('Perfume');
       }
       if(isset($_POST['Gillette']))
       {
        x('Gillette');
       }
       if(isset($_POST['HairColor']))
       {
        x('HairColor');
       }
       if(isset($_POST['SanitaryPads']))
       {
        x('SanitaryPads');
       }
       if(isset($_POST['Disinfectantspray']))
       {
        x('Disinfectantspray');
       }
       if(isset($_POST['Mouthwash']))
       {
        x('Mouthwash');
       }
       if(isset($_POST['Bodylotion']))
       {
        x('Bodylotion');
       }
       if(isset($_POST['Underarmrollon']))
       {
        x('Underarmrollon');
       }
       if(isset($_POST['SkinLiquid']))
       {
        x('SkinLiquid');
       }
      if(isset($_POST['Vim']))
      {
       x('Vim');
      }
      if(isset($_POST['SurfExcel']))
      {
       x('SurfExcel');
      }
      if(isset($_POST['Harpic']))
      {
       x('Harpic');
      }
      if(isset($_POST['Hit']))
      {
       x('Hit');
      }
      if(isset($_POST['GoodKnight']))
      {
       x('GoodKnight');
      }
      if(isset($_POST['FloorCleaner']))
      {
       x('FloorCleaner');
      }
      if(isset($_POST['VimGel']))
      {
       x('VimGel');
      }
      if(isset($_POST['Rin']))
      {
       x('Rin');
      }
      if(isset($_POST['Comfort']))
      {
       x('Comfort');
      }
      if(isset($_POST['Colin']))
      {
       x('Colin');
      }
      if(isset($_POST['Agarbatti']))
      {
       x('Agarbatti');
      }
      if(isset($_POST['Camphor']))
      {
       x('Camphor');
      }
      if(isset($_POST['Dhoop']))
      {
       x('Dhoop');
      }
      if(isset($_POST['Wick']))
      {
       x('Wick');
      }
      if(isset($_POST['PoojaOil']))
      {
       x('PoojaOil');
      }
      if(isset($_POST['Kumkuma']))
      {
       x('Kumkuma');
      }
      if(isset($_POST['GarbageBags']))
      {
       x('GarbageBags');
      }
      if(isset($_POST['SteelGrip']))
      {
       x('SteelGrip');
      }
     if(isset($_POST['jackfruit']))
     {
      x('jackfruit');
     }
     if(isset($_POST['pineapple']))
     {
      x('pineapple');
     }
     if(isset($_POST['pear']))
     {
      x('pear');
     }
     if(isset($_POST['Dragon']))
     {
      x('Dragon');
     }
     if(isset($_POST['Sapota']))
     {
      x('Sapota');
     }
     if(isset($_POST['Papaya']))
     {
      x('Papaya');
     }
     if(isset($_POST['Mango']))
     {
      x('Mango');
     }
     if(isset($_POST['Grapes']))
     {
      x('Grapes');
     }
     if(isset($_POST['Coconut']))
     {
      x('Coconut');
     }
     if(isset($_POST['Banana']))
     {
      x('Banana');
     }
     if(isset($_POST['WaterMelon']))
     {
      x('WaterMelon');
     }
     if(isset($_POST['Pomegranate']))
     {
      x('Pomegranate');
     }
     if(isset($_POST['Coconut-medium']))
     {
      x('Coconut-medium');
     }
     if(isset($_POST['Apple']))
     {
      x('Apple');
     }
     if(isset($_POST['Muskmelon']))
     {
      x('Muskmelon');
     }
     if(isset($_POST['Orange']))
     {
      x('Orange');
     }
     if(isset($_POST['Kiwi']))
     {
      x('Kiwi');
     }
     if(isset($_POST['Gauva']))
     {
      x('Gauva');
     }
     if(isset($_POST['Butter']))
     {
      x('Butter');
     }
     if(isset($_POST['Milk']))
     {
      x('Milk');
     }
     if(isset($_POST['Curd']))
     {
      x('Curd');
     }
     if(isset($_POST['Buttermilk']))
     {
      x('Buttermilk');
     }
     if(isset($_POST['Paneer']))
     {
      x('Paneer');
     }
     if(isset($_POST['Cheese']))
     {
      x('Cheese');
     }
     if(isset($_POST['Bread']))
     {
      x('Bread');
     }
     if(isset($_POST['Rusk']))
     {
      x('Rusk');
     }
     if(isset($_POST['Lassi']))
     {
      x('Lassi');
     }
     if(isset($_POST['Kool']))
     {
      x('Kool');
     }
     if(isset($_POST['Milkshake']))
     {
      x('Milkshake');
     }
     if(isset($_POST['Soyadrink']))
     {
      x('Soyadrink');
     }
     if(isset($_POST['Biscuits']))
     {
      x('Biscuits');
     }
     if(isset($_POST['SwissRoll']))
     {
      x('SwissRoll');
     }
     if(isset($_POST['Milkmaid']))
     {
      x('Milkmaid');
     }
     if(isset($_POST['Cupcake']))
     {
      x('Cupcake');
     }
     if(isset($_POST['Coffee']))
     {
      x('Coffee');
     }
     if(isset($_POST['Tea']))
     {
      x('Tea');
     }
    if(isset($_POST['ThumsUp']))
    {
     x('ThumsUp');
    }
    if(isset($_POST['Sprite']))
    {
     x('Sprite');
    }
    if(isset($_POST['Coketin']))
    {
     x('Coketin');
    }
    if(isset($_POST['Coke']))
    {
     x('Coke');
    }
    if(isset($_POST['Slice']))
    {
     x('Slice');
    }
    if(isset($_POST['Pepsitin']))
    {
     x('Pepsitin');
    }
    if(isset($_POST['Limca']))
    {
     x('Limca');
    }
    if(isset($_POST['Horlicks']))
    {
     x('Horlicks');
    }
    if(isset($_POST['Tang']))
    {
     x('Tang');
    }
    if(isset($_POST['Maaza']))
    {
     x('Maaza');
    }
    if(isset($_POST['Bournvita']))
    {
     x('Bournvita');
    }
    if(isset($_POST['Dew']))
    {
     x('Dew');
    }
    if(isset($_POST['Soda']))
    {
     x('Soda');
    }
    if(isset($_POST['BNatural']))
    {
     x('BNatural');
    }
    if(isset($_POST['7up']))
    {
     x('7up');
    }
    if(isset($_POST['GluconD']))
    {
     x('GluconD');
    }
    if(isset($_POST['Sharbat']))
    {
     x('Sharbat');
    }
    if(isset($_POST['Water']))
    {
     x('Water');
    }
    if(isset($_POST['Ceregrow']))
    {
     x('Ceregrow');
    }
    if(isset($_POST['Pampers']))
    {
     x('Pampers');
    }
    if(isset($_POST['BabyShampoo']))
    {
     x('BabyShampoo');
    }
    if(isset($_POST['BabyWash']))
    {
     x('BabyWash');
    }
    if(isset($_POST['BabyPowder']))
    {
     x('BabyPowder');
    }
    if(isset($_POST['Cerelac']))
    {
     x('Cerelac');
    }
    if(isset($_POST['BabySoap']))
    {
     x('BabySoap');
    }
    if(isset($_POST['KidsToothpaste']))
    {
     x('KidsToothpaste');
    }
    if(isset($_POST['MotherPlus']))
    {
     x('MotherPlus');
    }
    if(isset($_POST['Mamy']))
    {
     x('Mamy');
    }
    if(isset($_POST['BabyCream']))
    {
     x('BabyCream');
    }
    if(isset($_POST['Lactogen']))
    {
     x('Lactogen');
    }
    if(isset($_POST['FeedingBottle']))
    {
     x('FeedingBottle');
    }
    if(isset($_POST['Napkin']))
    {
     x('Napkin');
    }
    if(isset($_POST['CareCollection']))
    {
     x('CareCollection');
    }
    if(isset($_POST['Zookers']))
    {
     x('Zookers');
    }
    if(isset($_POST['BabyMassageoil']))
    {
     x('BabyMassageoil');
    }
    if(isset($_POST['Huggies']))
    {
     x('Huggies');
    }
    function x($var)
    {
       $a=$var;
       $b= $_POST[$a."price"];
       $c= $_POST[$a."quantity"];
       $price=$b*$c;
       $det=array('Fruit Name'=>$a,$a.'-quantity'=>$c,$a.'-cost'=>$b,$a.'-price'=>$price);
       $_SESSION[$a]=json_encode($det);
    }
?>